name = "BZIntegral"
uuid = "aa467f8f-0a01-46b4-8fec-c7f668a281fb"
authors = ["Yihao"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
